# Generated by Django 3.0.3 on 2020-11-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_remove_contact2_textarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact2',
            new_name='Contact',
        ),
    ]
